In [1]:
import pandas as pd
import numpy as np

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "cars24data.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "amanrajput16/used-car-price-data-from-cars24",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\DELL\AppData\Local\Temp\ipykernel_14452\4191626381.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to C:\Users\DELL\.cache\kagglehub\datasets\amanrajput16\used-car-price-data-from-cars24\versions\1\cars24data.csv...

100%|████████████████████████████████████████████████████████████████████████████████| 111k/111k [00:00<00:00, 191kB/s]

First 5 records:                             Model Name    Price  Manufacturing_year  \
0                2017 Maruti Swift VXI   561000                2017
1  2016 Maruti Baleno DELTA PETROL 1.2   498000                2016
2                2020 Maruti Swift VXI   577000                2020
3       2022 Maruti Ertiga VXI AT SHVS  1084000                2022
4                2019 Maruti Dzire VXI   603000                2019

   Engine capacity Spare key Transmission  KM driven  Ownership Fuel type  \
0             1197        No       Manual      25847          2    Petrol
1             1197       Yes       Manual      55511          2    Petrol
2             1197        No       Manual      47110          1    Petrol
3             1462       Yes    Automatic      35378          1    Petrol
4             1197       Yes       Manual      91856          1    Petrol

   Imperfections  Repainted Parts
0              6                2
1             12                1
2              4                2
3              2                3
4              3                2

In [3]:
df

,Model Name,Price,Manufacturing_year,Engine capacity,Spare key,Transmission,KM driven,Ownership,Fuel type,Imperfections,Repainted Parts
0,2017 Maruti Swift VXI,561000,2017,1197,No,Manual,25847,2,Petrol,6,2
1,2016 Maruti Baleno DELTA PETROL 1.2,498000,2016,1197,Yes,Manual,55511,2,Petrol,12,1
2,2020 Maruti Swift VXI,577000,2020,1197,No,Manual,47110,1,Petrol,4,2
3,2022 Maruti Ertiga VXI AT SHVS,1084000,2022,1462,Yes,Automatic,35378,1,Petrol,2,3
4,2019 Maruti Dzire VXI,603000,2019,1197,Yes,Manual,91856,1,Petrol,3,2
...,...,...,...,...,...,...,...,...,...,...,...
1440,2021 Maruti Ertiga VXI SHVS,862000,2021,1462,No,Manual,19901,1,Petrol,1,0
1441,2015 Maruti Ciaz ZXI,507000,2015,1373,No,Manual,50022,1,Petrol,5,2
1442,2019 Maruti Baleno DELTA PETROL 1.2,554000,2019,1197,Yes,Manual,58679,1,Petrol,24,4
1443,2017 Maruti Ciaz S 1.4 MT PETROL,557000,2017,1373,Yes,Manual,73948,2,Petrol,4,5
1444,2012 Maruti Wagon R 1.0 LXI,256000,2012,998,No,Manual,55994,1,Petrol,20,9

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Model Name          1445 non-null   str
 1   Price               1445 non-null   int64
 2   Manufacturing_year  1445 non-null   int64
 3   Engine capacity     1445 non-null   int64
 4   Spare key           1445 non-null   str
 5   Transmission        1445 non-null   str
 6   KM driven           1445 non-null   int64
 7   Ownership           1445 non-null   int64
 8   Fuel type           1445 non-null   str
 9   Imperfections       1445 non-null   int64
 10  Repainted Parts     1445 non-null   int64
dtypes: int64(7), str(4)
memory usage: 124.3 KB

In [5]:
df.describe()

,Price,Manufacturing_year,Engine capacity,KM driven,Ownership,Imperfections,Repainted Parts
count,1.445000e+03,1445.000000,1445.000000,1445.000000,1445.000000,1445.000000,1445.000000
mean,5.263543e+05,2017.817301,1142.104498,50588.903114,1.285121,9.597232,3.228374
std,1.963696e+05,2.986554,169.020818,27339.562631,0.489877,8.398637,3.364578
min,1.390000e+05,2010.000000,796.000000,1207.000000,1.000000,0.000000,0.000000
25%,3.900000e+05,2016.000000,998.000000,28803.000000,1.000000,3.000000,0.000000
50%,5.010000e+05,2018.000000,1197.000000,47849.000000,1.000000,8.000000,2.000000
75%,6.310000e+05,2020.000000,1197.000000,70337.000000,2.000000,14.000000,5.000000
max,1.599000e+06,2023.000000,1462.000000,124716.000000,3.000000,43.000000,27.000000

In [6]:
df.head()

,Model Name,Price,Manufacturing_year,Engine capacity,Spare key,Transmission,KM driven,Ownership,Fuel type,Imperfections,Repainted Parts
0,2017 Maruti Swift VXI,561000,2017,1197,No,Manual,25847,2,Petrol,6,2
1,2016 Maruti Baleno DELTA PETROL 1.2,498000,2016,1197,Yes,Manual,55511,2,Petrol,12,1
2,2020 Maruti Swift VXI,577000,2020,1197,No,Manual,47110,1,Petrol,4,2
3,2022 Maruti Ertiga VXI AT SHVS,1084000,2022,1462,Yes,Automatic,35378,1,Petrol,2,3
4,2019 Maruti Dzire VXI,603000,2019,1197,Yes,Manual,91856,1,Petrol,3,2

In [7]:
df.tail()

,Model Name,Price,Manufacturing_year,Engine capacity,Spare key,Transmission,KM driven,Ownership,Fuel type,Imperfections,Repainted Parts
1440,2021 Maruti Ertiga VXI SHVS,862000,2021,1462,No,Manual,19901,1,Petrol,1,0
1441,2015 Maruti Ciaz ZXI,507000,2015,1373,No,Manual,50022,1,Petrol,5,2
1442,2019 Maruti Baleno DELTA PETROL 1.2,554000,2019,1197,Yes,Manual,58679,1,Petrol,24,4
1443,2017 Maruti Ciaz S 1.4 MT PETROL,557000,2017,1373,Yes,Manual,73948,2,Petrol,4,5
1444,2012 Maruti Wagon R 1.0 LXI,256000,2012,998,No,Manual,55994,1,Petrol,20,9

In [8]:
df.isnull().sum()

Model Name            0
Price                 0
Manufacturing_year    0
Engine capacity       0
Spare key             0
Transmission          0
KM driven             0
Ownership             0
Fuel type             0
Imperfections         0
Repainted Parts       0
dtype: int64

In [9]:
df.notnull().sum()

Model Name            1445
Price                 1445
Manufacturing_year    1445
Engine capacity       1445
Spare key             1445
Transmission          1445
KM driven             1445
Ownership             1445
Fuel type             1445
Imperfections         1445
Repainted Parts       1445
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["Model Name"].unique().value_counts()

2017 Maruti Swift VXI                  1
2016 Maruti Baleno DELTA PETROL 1.2    1
2020 Maruti Swift VXI                  1
2022 Maruti Ertiga VXI AT SHVS         1
2019 Maruti Dzire VXI                  1
                                      ..
2017 Maruti IGNIS DELTA 1.2 AMT        1
2017 Maruti Eeco 5 STR WITH A/C+HTR    1
2019 Maruti New Wagon-R VXI 1.0        1
2021 Maruti Ertiga VXI SHVS            1
2017 Maruti Ciaz S 1.4 MT PETROL       1
Name: count, Length: 573, dtype: int64

In [17]:
df.columns

Index(['Model Name', 'Price', 'Manufacturing_year', 'Engine capacity',
       'Spare key', 'Transmission', 'KM driven', 'Ownership', 'Fuel type',
       'Imperfections', 'Repainted Parts'],
      dtype='str')

In [19]:
mean_price = df["Price"].mean()
mean_price

np.float64(526354.3252595155)

In [21]:
mode_year = df["Manufacturing_year"].mode()
mode_year

0    2017
Name: Manufacturing_year, dtype: int64

In [25]:
sort_price = df.sort_values(["Manufacturing_year" ,"Price"])
sort_price

,Model Name,Price,Manufacturing_year,Engine capacity,Spare key,Transmission,KM driven,Ownership,Fuel type,Imperfections,Repainted Parts
1126,2010 Maruti A Star LXI,208000,2010,998,No,Manual,103867,2,Petrol,35,10
906,2011 Maruti Alto K10 VXI,139000,2011,998,No,Manual,83452,1,Petrol,27,5
723,2011 Maruti Alto K10 VXI,154000,2011,998,No,Manual,63048,1,Petrol,33,3
637,2011 Maruti Wagon R 1.0 LX,162000,2011,998,No,Manual,93282,1,Petrol,35,10
422,2011 Maruti Alto K10 VXI,170000,2011,998,No,Manual,123621,2,Petrol,25,6
...,...,...,...,...,...,...,...,...,...,...,...
347,2023 Maruti XL6 ZETA CNG,1225000,2023,1462,Yes,Manual,21141,1,CNG,0,0
243,2023 Maruti XL6 ZETA CNG,1228000,2023,1462,Yes,Manual,32447,1,CNG,1,0
359,2023 Maruti BREZZA ZXI SMART HYBRID,1231000,2023,1462,Yes,Manual,10234,1,Petrol,0,0
494,2023 Maruti XL6 ALPHA PLUS MT,1258000,2023,1462,Yes,Manual,28161,1,Petrol,1,0
1170,2023 Maruti Ertiga ZXI+ AT SHVS,1364000,2023,1462,No,Automatic,11016,1,Petrol,0,0

In [27]:
fuel_group = df.groupby("Fuel type")
fuel_group

In [28]:
df["Engine capacity"].max()

np.int64(1462)

In [29]:
df["Engine capacity"].idxmax()

3

In [30]:
df.iloc[3 , :]

Model Name            2022 Maruti Ertiga VXI AT SHVS
Price                                        1084000
Manufacturing_year                              2022
Engine capacity                                 1462
Spare key                                        Yes
Transmission                               Automatic
KM driven                                      35378
Ownership                                          1
Fuel type                                     Petrol
Imperfections                                      2
Repainted Parts                                    3
Name: 3, dtype: object

In [31]:
df.iloc[df["Engine capacity"].idxmax() , :]

Model Name            2022 Maruti Ertiga VXI AT SHVS
Price                                        1084000
Manufacturing_year                              2022
Engine capacity                                 1462
Spare key                                        Yes
Transmission                               Automatic
KM driven                                      35378
Ownership                                          1
Fuel type                                     Petrol
Imperfections                                      2
Repainted Parts                                    3
Name: 3, dtype: object

In [32]:
df["Engine capacity"].min()

np.int64(796)

In [33]:
df["Engine capacity"].idxmin()

5

In [34]:
df.iloc[df["Engine capacity"].idxmin() , :]

Model Name            2014 Maruti Alto 800 LXI
Price                                   233000
Manufacturing_year                        2014
Engine capacity                            796
Spare key                                   No
Transmission                            Manual
KM driven                                43780
Ownership                                    1
Fuel type                               Petrol
Imperfections                               10
Repainted Parts                              2
Name: 5, dtype: object

In [35]:
df["Price"].agg(["mean", "max", "median"])

mean      5.263543e+05
max       1.599000e+06
median    5.010000e+05
Name: Price, dtype: float64

In [38]:
df["Model Name"].shape[0]

1445

In [42]:
df["Fuel type"].unique()

<StringArray>
['Petrol', 'Diesel', 'CNG']
Length: 3, dtype: str

In [43]:
df["Fuel type"].mode()

0    Petrol
Name: Fuel type, dtype: str

In [46]:
df["Transmission"].mode()

0    Manual
Name: Transmission, dtype: str

In [47]:
df["KM driven"].mean()

np.float64(50588.903114186855)

In [48]:
df["Price"].max()

np.int64(1599000)

In [49]:
df["Price"].min()

np.int64(139000)

In [50]:
fuel_group["Price"].mean()

Fuel type
CNG       475807.339450
Diesel    589111.111111
Petrol    527138.449367
Name: Price, dtype: float64

In [52]:
Transmission_group = df.groupby("Transmission")
Transmission_group

In [57]:
Transmission_group["Price"].agg(["mean", "max", "min", "count"])

                       mean      max     min  count
Transmission
Automatic     601338.709677  1408000  265000    372
Manual        500357.875116  1599000  139000   1073

In [60]:
df["Model Name"].value_counts().head()

Model Name
2015 Maruti Wagon R 1.0 VXI            16
2014 Maruti Swift VXI                  14
2017 Maruti Baleno ALPHA PETROL 1.2    14
2017 Maruti Baleno DELTA PETROL 1.2    14
2016 Maruti Swift VXI                  14
Name: count, dtype: int64

In [64]:

sort_price2 = df.sort_values(["Price"])
sort_price2.tail(1)

,Model Name,Price,Manufacturing_year,Engine capacity,Spare key,Transmission,KM driven,Ownership,Fuel type,Imperfections,Repainted Parts
1056,2022 Maruti Grand Vitara ALPHA SMART HYBRID AL...,1599000,2022,1462,Yes,Manual,14358,1,Petrol,3,0