In [4]:
import pandas as pd

In [5]:
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [24, 27, 22],
'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [6]:
df.head()

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [7]:
df.tail()

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [8]:
df.head(1)

    Name  Age      City
0  Alice   24  New York

In [9]:
df.tail(1)

      Name  Age     City
2  Charlie   22  Chicago

In [10]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes
None

In [11]:
print(df.describe())

             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

In [12]:
#single cilimn
print(df["Name"])
#multy colomns

print(df[["Name", "City"]])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str
      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

In [13]:
#first row #retriev data by index
print(df.iloc[0])

Name       Alice
Age           24
City    New York
Name: 0, dtype: object

In [14]:
#row whith index
print(df.loc[1])

Name            Bob
Age              27
City    Los Angeles
Name: 1, dtype: object

In [15]:
pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (0.1.19)
Requirement already satisfied: packaging in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2025.4.26)
Requirement already satisfied: colorama in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data_science_student_marks.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sudhirsingh108/data-science-students",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\DELL\AppData\Local\Temp\ipykernel_16108\513364880.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:    student_id location  age  sql_marks  excel_marks  python_marks  \
0           4   Sydney   24         95           99            87
1           5    Tokyo   24         99           95            89
2           6   Berlin   22         72           70            99
3           7   London   23         97           90            74
4           8    Tokyo   22         91           71            79

   power_bi_marks  english_marks
0              82             75
1              86             82
2              79             77
3              72             85
4              80             75

In [17]:
df.head(2)

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82

In [18]:
df.tail(2)

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
495,499,Los Angeles,21,96,93,78,78,82
496,500,London,22,85,87,93,70,86

In [19]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      497 non-null    int64
 1   location        497 non-null    str
 2   age             497 non-null    int64
 3   sql_marks       497 non-null    int64
 4   excel_marks     497 non-null    int64
 5   python_marks    497 non-null    int64
 6   power_bi_marks  497 non-null    int64
 7   english_marks   497 non-null    int64
dtypes: int64(7), str(1)
memory usage: 31.2 KB
None

In [20]:
print(df.describe())

       student_id         age   sql_marks  excel_marks  python_marks  \
count  497.000000  497.000000  497.000000   497.000000    497.000000
mean   252.000000   21.380282   84.661972    85.384306     85.388330
std    143.615807    2.205714    8.745415     8.782497      8.878668
min      4.000000   18.000000   70.000000    70.000000     70.000000
25%    128.000000   20.000000   78.000000    78.000000     77.000000
50%    252.000000   21.000000   85.000000    86.000000     86.000000
75%    376.000000   23.000000   92.000000    93.000000     94.000000
max    500.000000   25.000000  100.000000   100.000000    100.000000

       power_bi_marks  english_marks
count      497.000000     497.000000
mean        84.545272      84.824950
std          8.903066       9.060479
min         70.000000      70.000000
25%         77.000000      77.000000
50%         84.000000      85.000000
75%         92.000000      93.000000
max        100.000000     100.000000

In [21]:
print(df.iloc[0]) #givs row and col by there indexs

student_id             4
location          Sydney
age                   24
sql_marks             95
excel_marks           99
python_marks          87
power_bi_marks        82
english_marks         75
Name: 0, dtype: object

In [22]:
print(df.loc[1]) #givs row and col by there labls(names)

student_id            5
location          Tokyo
age                  24
sql_marks            99
excel_marks          95
python_marks         89
power_bi_marks       86
english_marks        82
Name: 1, dtype: object

In [23]:
print(df.loc[2])

student_id             6
location          Berlin
age                   22
sql_marks             72
excel_marks           70
python_marks          99
power_bi_marks        79
english_marks         77
Name: 2, dtype: object

In [24]:

locations = df["location"]
print(locations)

0           Sydney
1            Tokyo
2           Berlin
3           London
4            Tokyo
          ...
492       New York
493    Los Angeles
494          Paris
495    Los Angeles
496         London
Name: location, Length: 497, dtype: str

In [25]:
locations.unique()

<StringArray>
[     'Sydney',       'Tokyo',      'Berlin',      'London',     'Toronto',
   'Melbourne',       'Paris', 'Los Angeles',    'New York']
Length: 9, dtype: str

In [26]:
locations.value_counts()

location
Tokyo          60
Los Angeles    60
Melbourne      58
New York       57
Toronto        56
Paris          55
Sydney         53
Berlin         52
London         46
Name: count, dtype: int64

In [27]:
sql_marks = df["sql_marks"]
sql_marks.mean()

np.float64(84.66197183098592)

In [29]:
df.iloc[[1,6]]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
1,5,Tokyo,24,99,95,89,86,82
6,10,Tokyo,18,77,87,100,98,93

In [30]:
df.iloc[1:6 , 0:2]

   student_id location
1           5    Tokyo
2           6   Berlin
3           7   London
4           8    Tokyo
5           9  Toronto

In [33]:
english_student = df.iloc[ : , 7]
english_student

0      75
1      82
2      77
3      85
4      75
       ..
492    88
493    73
494    70
495    82
496    86
Name: english_marks, Length: 497, dtype: int64

In [34]:
english_student.mean()

np.float64(84.82494969818913)

In [35]:
english_student.max()

np.int64(100)

In [37]:
english_student.idxmax()

19

In [38]:
english_student.idxmin()

52

In [39]:
print(df.iloc[1:4, [0,2]])

   student_id  age
1           5   24
2           6   22
3           7   23

In [40]:
df["age"].mean()

np.float64(21.380281690140844)

In [41]:
df["age"]

0      24
1      24
2      22
3      23
4      22
       ..
492    23
493    20
494    22
495    21
496    22
Name: age, Length: 497, dtype: int64

In [43]:
df.iloc[: , 2].mean

<bound method Series.mean of 0      24
1      24
2      22
3      23
4      22
       ..
492    23
493    20
494    22
495    21
496    22
Name: age, Length: 497, dtype: int64>

In [44]:
df["age"].value_counts()

age
21    76
19    72
20    68
22    65
23    60
25    60
18    52
24    44
Name: count, dtype: int64

In [45]:
df["location"].value_counts()

location
Tokyo          60
Los Angeles    60
Melbourne      58
New York       57
Toronto        56
Paris          55
Sydney         53
Berlin         52
London         46
Name: count, dtype: int64

In [49]:
df.loc[0,"student_id"]

np.int64(4)

In [50]:
df.loc[0,["student_id" , "age"]]

student_id     4
age           24
Name: 0, dtype: int64

In [52]:
df.loc[0:3,["student_id" , "age"]]

   student_id  age
0           4   24
1           5   24
2           6   22
3           7   23

In [53]:
df.loc[[10,20],["student_id" , "age"]]

    student_id  age
10          14   20
20          24   20

In [57]:
df.loc[df["age"] > 23]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
8,12,Melbourne,24,80,95,87,90,94
11,15,Paris,24,94,93,87,80,71
13,17,Tokyo,25,82,75,77,78,85
...,...,...,...,...,...,...,...,...
485,489,Los Angeles,24,70,89,81,91,70
487,491,Melbourne,25,75,77,82,99,83
489,493,Los Angeles,24,94,74,80,92,95
490,494,Melbourne,25,84,96,72,93,86
491,495,New York,24,83,78,82,84,84

In [59]:
num_age_apove23 =df.loc[df["age"] > 23].shape
num_age_apove23

(104, 8)

In [67]:
#number of students got > 95 in python

df.loc[df["python_marks"] > 95].shape

(84, 8)

In [68]:
#the percintage of students got > 95 in python 
#(df.shape[0] * 100) is the nymber of all students in python

df.loc[df["python_marks"] > 95].shape[0] / df.shape[0] * 100

16.901408450704224

In [69]:
df.columns

Index(['student_id', 'location', 'age', 'sql_marks', 'excel_marks',
       'python_marks', 'power_bi_marks', 'english_marks'],
      dtype='str')

In [79]:

c1 =df["age"]>= 22 
c2 = df["age"] <= 24
df[c1 & c2]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
489,493,Los Angeles,24,94,74,80,92,95
491,495,New York,24,83,78,82,84,84
492,496,New York,23,71,92,98,78,88
494,498,Paris,22,78,80,78,71,70
496,500,London,22,85,87,93,70,86

In [88]:
con1 = df["excel_marks"] > 90
con2 = df["sql_marks"] > 90
result = df[con1 & con2].shape
result

(41, 8)

In [90]:
df["location"].replace("London" , "LON")

0           Sydney
1            Tokyo
2           Berlin
3              LON
4            Tokyo
          ...
492       New York
493    Los Angeles
494          Paris
495    Los Angeles
496            LON
Name: location, Length: 497, dtype: str

In [91]:
df.set_index("student_id")

,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
student_id,,,,,,,
4,Sydney,24,95,99,87,82,75
5,Tokyo,24,99,95,89,86,82
6,Berlin,22,72,70,99,79,77
7,London,23,97,90,74,72,85
8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...
496,New York,23,71,92,98,78,88
497,Los Angeles,20,90,100,90,78,73
498,Paris,22,78,80,78,71,70
499,Los Angeles,21,96,93,78,78,82
500,London,22,85,87,93,70,86

In [92]:
df.rename(columns = {"location" : "country"})

,student_id,country,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,London,22,85,87,93,70,86

In [95]:
isin_country = df[df["location"].isin(["Tokyo" , "Sydney"])]
isin_country

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
4,8,Tokyo,22,91,71,79,80,75
6,10,Tokyo,18,77,87,100,98,93
12,16,Tokyo,19,73,82,78,70,84
...,...,...,...,...,...,...,...,...
465,469,Sydney,20,86,99,82,92,88
467,471,Tokyo,22,94,71,84,87,70
474,478,Tokyo,21,98,89,94,75,97
477,481,Sydney,24,70,79,80,83,78
486,490,Tokyo,18,87,100,95,89,85

In [96]:
df[df["age"].between(20,23)]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
5,9,Toronto,20,93,88,75,93,72
7,11,Toronto,21,78,90,88,79,72
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,London,22,85,87,93,70,86

In [98]:
df.isnull().sum

<bound method DataFrame.sum of      student_id  location    age  sql_marks  excel_marks  python_marks  \
0         False     False  False      False        False         False
1         False     False  False      False        False         False
2         False     False  False      False        False         False
3         False     False  False      False        False         False
4         False     False  False      False        False         False
..          ...       ...    ...        ...          ...           ...
492       False     False  False      False        False         False
493       False     False  False      False        False         False
494       False     False  False      False        False         False
495       False     False  False      False        False         False
496       False     False  False      False        False         False

     power_bi_marks  english_marks
0             False          False
1             False          False
2             False          False
3             False          False
4             False          False
..              ...            ...
492           False          False
493           False          False
494           False          False
495           False          False
496           False          False

[497 rows x 8 columns]>

In [104]:
import numpy as np
df.loc[0,"location"]=np.nan
df

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks,country
0,4,NaN,24,95,99,87,82,75,NaN
1,5,Tokyo,24,99,95,89,86,82,NaN
2,6,Berlin,22,72,70,99,79,77,NaN
3,7,London,23,97,90,74,72,85,NaN
4,8,Tokyo,22,91,71,79,80,75,NaN
...,...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88,NaN
493,497,Los Angeles,20,90,100,90,78,73,NaN
494,498,Paris,22,78,80,78,71,70,NaN
495,499,Los Angeles,21,96,93,78,78,82,NaN
496,500,London,22,85,87,93,70,86,NaN

In [106]:
df.fillna({"location" : df["location"].mode() } , inplace = True)
#replacing nan with the mode value

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks,country
0,4,Los Angeles,24,95,99,87,82,75,NaN
1,5,Tokyo,24,99,95,89,86,82,NaN
2,6,Berlin,22,72,70,99,79,77,NaN
3,7,London,23,97,90,74,72,85,NaN
4,8,Tokyo,22,91,71,79,80,75,NaN
...,...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88,NaN
493,497,Los Angeles,20,90,100,90,78,73,NaN
494,498,Paris,22,78,80,78,71,70,NaN
495,499,Los Angeles,21,96,93,78,78,82,NaN
496,500,London,22,85,87,93,70,86,NaN

In [108]:
df.duplicated().sum()

np.int64(0)

In [112]:
df.drop_duplicates()

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks,country
0,4,Los Angeles,24,95,99,87,82,75,NaN
1,5,Tokyo,24,99,95,89,86,82,NaN
2,6,Berlin,22,72,70,99,79,77,NaN
3,7,London,23,97,90,74,72,85,NaN
4,8,Tokyo,22,91,71,79,80,75,NaN
...,...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88,NaN
493,497,Los Angeles,20,90,100,90,78,73,NaN
494,498,Paris,22,78,80,78,71,70,NaN
495,499,Los Angeles,21,96,93,78,78,82,NaN
496,500,London,22,85,87,93,70,86,NaN

In [114]:
df["status_python"] = df["python_marks"].map(lambda x : "pass" if x >= 60 else "fail")
df["status_python"]

0      pass
1      pass
2      pass
3      pass
4      pass
       ...
492    pass
493    pass
494    pass
495    pass
496    pass
Name: status_python, Length: 497, dtype: str

In [117]:
###another way to do that:

df["status"] = np.where(df["python_marks"] >= 60, "pass", "fail")
df["status"]

0      pass
1      pass
2      pass
3      pass
4      pass
       ...
492    pass
493    pass
494    pass
495    pass
496    pass
Name: status, Length: 497, dtype: str

In [121]:
location_group = df.groupby("location")
location_group

In [124]:
location_group["python_marks"].mean()

location
Berlin         85.653846
London         85.521739
Los Angeles    85.557377
Melbourne      83.637931
New York       86.771930
Paris          85.381818
Sydney         84.230769
Tokyo          86.033333
Toronto        85.642857
Name: python_marks, dtype: float64

In [129]:
location_group["python_marks"].max()["Paris"]

np.int64(100)

In [130]:
location_group["python_marks"].idxmax()["Paris"]

np.int64(264)

In [126]:
location_group["python_marks"].agg(["mean", "std", "count"])

                  mean        std  count
location
Berlin       85.653846   8.590658     52
London       85.521739   9.396782     46
Los Angeles  85.557377   8.872288     61
Melbourne    83.637931   9.561800     58
New York     86.771930   8.174476     57
Paris        85.381818   8.807595     55
Sydney       84.230769  10.075432     52
Tokyo        86.033333   8.188389     60
Toronto      85.642857   8.499045     56